'use client'
/* Node relationship map: circle-pack of settlement points (zone -> substation
   -> point, sized by live CRR MW or avg |basis|) with bundled edges for live
   CRR paths, constraint cheap->expensive links, and shared-driver pairs.
   Data: /node_graph.json, regenerated by scripts/build_node_graph.py. */
import { useMemo, useRef, useState, useEffect } from 'react'
import * as d3 from 'd3'

const KINDS: Record<string, { label: string; color: string }> = {
  crr: { label: 'Live CRR path', color: '#22d3ee' },
  congestion: { label: 'Constraint (cheap→expensive)', color: '#f43f5e' },
  shareddrv: { label: 'Shared driver', color: '#6366f1' },
}

type Link = { source: string; target: string; kind: string; value: number; label?: string }
type Graph = { tree: any; links: Link[]; asOf: string; points: number }
type GeoPath = { a: [number, number]; b: [number, number]; v: number; label: string }
type GeoLayer = {
  nodes: { name: string; lat: number; lon: number; mw: number; tier: string }[]
  grid: [number, number][][]
  crr: GeoPath[]
  constraints: { name: string; lat: number; lon: number }[]
  paths?: { market?: Record<string, GeoPath[]>; steve?: Record<string, GeoPath[]>;
            suggestions?: Record<string, GeoPath[]> }
  asOf: string
}

const SCOPES = [
  ['market', 'Whole market'],
  ['steve', "Steve's book"],
  ['suggestions', 'Bid-sheet picks'],
] as const

function GridView({ geo, tx }: { geo: GeoLayer; tx: any }) {
  const [hover, setHover] = useState<string | null>(null)
  const [scope, setScope] = useState<'market' | 'steve' | 'suggestions'>('market')
  const months = useMemo(
    () => Object.keys(geo.paths?.market ?? {}).sort(),
    [geo])
  const [month, setMonth] = useState<string>('')
  useEffect(() => { if (!month && months.length) setMonth(months[0]) }, [months, month])

  const shown: GeoPath[] = useMemo(() => {
    if (!geo.paths) return geo.crr
    if (scope === 'suggestions') return geo.paths.suggestions?.all ?? []
    return geo.paths[scope]?.[month] ?? []
  }, [geo, scope, month])
  const W = 860, H = 820
  const proj = useMemo(() => {
    const p = d3.geoMercator()
    p.fitExtent([[10, 10], [W - 10, H - 10]], tx)
    return p
  }, [tx])
  const path = useMemo(() => d3.geoPath(proj), [proj])
  const pt = (lat: number, lon: number) => proj([lon, lat]) ?? [0, 0]
  const mwMax = Math.max(...geo.nodes.map(n => n.mw), 1)

  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-2 flex flex-wrap items-center gap-2 text-xs">
        {SCOPES.map(([k, label]) => (
          <button key={k} onClick={() => setScope(k)}
            className="rounded px-1.5 py-0.5"
            style={{ background: scope === k ? '#1e3038' : 'transparent',
                     color: scope === k ? '#f2f6f6' : '#7d9096' }}>
            {label}
          </button>
        ))}
        {scope !== 'suggestions' && months.length > 0 && (
          <select value={month} onChange={e => setMonth(e.target.value)}
            className="rounded border border-line bg-panel px-1.5 py-0.5 text-[#dbe4e6]">
            {months.map(m => <option key={m} value={m}>{m}</option>)}
          </select>
        )}
        <span className="text-[#61767e]">
          {shown.length} paths{scope === 'suggestions' ? ' (current auction scan)' : month ? ` live in ${month}` : ''}
        </span>
      </div>
      <svg viewBox={`0 0 ${W} ${H}`} width="100%" className="block select-none"
           onMouseLeave={() => setHover(null)}>
        <path d={path(tx as any) ?? undefined} fill="#101c22" stroke="#2c424c" strokeWidth={1} />
        <g stroke="#24404b" strokeWidth={0.6}>
          {geo.grid.map((e, i) => {
            const [a, b] = [pt(e[0][0], e[0][1]), pt(e[1][0], e[1][1])]
            return <line key={i} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} />
          })}
        </g>
        <g>
          {shown.map((c, i) => {
            const [a, b] = [pt(c.a[0], c.a[1]), pt(c.b[0], c.b[1])]
            const lit = !hover || c.label.includes(hover)
            const color = scope === 'steve' ? '#fbbf24' : scope === 'suggestions' ? '#a78bfa' : '#22d3ee'
            return (
              <line key={i} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]}
                stroke={color} strokeWidth={Math.max(1, c.v / 3)}
                strokeOpacity={lit ? 0.55 : 0.08} strokeLinecap="round" />
            )
          })}
        </g>
        <g>
          {geo.constraints.map((c, i) => {
            const [x, y] = pt(c.lat, c.lon)
            return (
              <g key={i} onMouseEnter={() => setHover(c.name)}>
                <circle cx={x} cy={y} r={5} fill="none" stroke="#f43f5e" strokeWidth={1.5} />
                <circle cx={x} cy={y} r={1.5} fill="#f43f5e" />
              </g>
            )
          })}
        </g>
        <g>
          {geo.nodes.map((n, i) => {
            const [x, y] = pt(n.lat, n.lon)
            const r = 2 + 8 * Math.sqrt(n.mw / mwMax)
            const isH = hover === n.name
            return (
              <g key={i} onMouseEnter={() => setHover(n.name)} style={{ cursor: 'pointer' }}>
                <circle cx={x} cy={y} r={r}
                  fill={isH ? '#f2f6f6' : n.tier === 'A' ? '#34d399' : n.tier === 'B' ? '#93a6ab' : '#3a4f58'}
                  fillOpacity={isH ? 1 : 0.8} stroke="#101c22" strokeWidth={0.5} />
                {(isH || r > 8) && (
                  <text x={x} y={y - r - 3} textAnchor="middle" fontSize={9}
                    fill={isH ? '#fafafa' : '#a1a1aa'} pointerEvents="none">{n.name}</text>
                )}
              </g>
            )
          })}
        </g>
      </svg>
      <div className="mt-2 flex items-center gap-4 text-[11px] text-[#7d9096]">
        <span><span className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-400" />exact location</span>
        <span><span className="mr-1 inline-block h-2 w-2 rounded-full bg-neutral-500" />name-matched</span>
        <span><span className="mr-1 inline-block h-2 w-2 rounded-full bg-neutral-700" />approximate</span>
        <span className="text-cyan-400">— live CRR paths</span>
        <span className="text-rose-400">◦ placeable constraints</span>
        <span className="ml-auto">{hover ?? 'grid edges derive from line-flow topology'}</span>
      </div>
    </div>
  )
}

export default function NodeMapPage() {
  const wrapRef = useRef<HTMLDivElement>(null)
  const [graph, setGraph] = useState<Graph | null>(null)
  const [geo, setGeo] = useState<GeoLayer | null>(null)
  const [tx, setTx] = useState<any>(null)
  const [view, setView] = useState<'grid' | 'rel'>('grid')
  const [size, setSize] = useState(760)
  const [hover, setHover] = useState<string | null>(null)
  const [off, setOff] = useState<Set<string>>(() => new Set())
  const [sizeBy, setSizeBy] = useState<'mw' | 'dart'>('mw')

  useEffect(() => {
    const grab = (name: string, fallback: string) =>
      fetch(`/api/artifact/${name}`)
        .then(r => (r.ok ? r.json() : fetch(fallback).then(f => f.json())))
        .catch(() => fetch(fallback).then(f => f.json()).catch(() => null))
    grab('node_graph', '/node_graph.json').then(setGraph)
    grab('grid_geo', '/grid_geo.json').then(setGeo)
    fetch('/tx.json').then(r => r.json()).then(setTx).catch(() => setTx(null))
  }, [])

  useEffect(() => {
    if (!wrapRef.current) return
    const ro = new ResizeObserver(([e]) => setSize(Math.max(320, Math.min(900, e.contentRect.width))))
    ro.observe(wrapRef.current)
    return () => ro.disconnect()
  }, [])

  const { leaves, circles, paths } = useMemo(() => {
    if (!graph) return { leaves: [], circles: [], paths: [] as any[] }
    const root = d3.hierarchy(graph.tree)
      .sum((d: any) => d[sizeBy] || 0)
      .sort((a: any, b: any) => (b.value || 0) - (a.value || 0))
    d3.pack().size([size, size]).padding(10)(root as any)

    const byName = new Map<string, any>()
    root.leaves().forEach((n: any) => byName.set(n.data.name, n))
    const line = d3.line().curve(d3.curveBundle.beta(0.9)).x((d: any) => d.x).y((d: any) => d.y)

    const paths = graph.links.map((l, i) => {
      const s = byName.get(l.source); const t = byName.get(l.target)
      if (!s || !t) return null
      return { id: `${l.source}->${l.target}-${i}`, d: line(s.path(t) as any),
               source: l.source, target: l.target, kind: l.kind, value: l.value, label: l.label }
    }).filter(Boolean) as any[]

    return { leaves: root.leaves() as any[], circles: root.descendants() as any[], paths }
  }, [graph, size, sizeBy])

  const visible = (p: any) => !off.has(p.kind)
  const lit = (p: any) => !hover || p.source === hover || p.target === hover
  const nodeLit = (name: string) =>
    !hover || name === hover ||
    paths.some(p => visible(p) &&
      ((p.source === hover && p.target === name) || (p.target === hover && p.source === name)))

  const toggle = (k: string) => setOff(prev => {
    const next = new Set(prev); next.has(k) ? next.delete(k) : next.add(k); return next
  })

  if (!graph) return <div className="p-6 text-[#93a6ab] text-sm">loading node graph…</div>

  const hoverNode = leaves.find(n => n.data.name === hover)
  const hoverLinks = paths.filter(p => visible(p) && (p.source === hover || p.target === hover))

  return (
    <div className="min-h-screen w-full bg-ink text-[#f2f6f6] p-4 font-sans">
      <div className="mb-1 flex items-baseline gap-3">
        <span className="text-sm font-semibold tracking-tight">
          {view === 'grid' ? 'The grid — nodes, lines, live paths' : 'Settlement point relationships'}
        </span>
        <span className="flex gap-1 text-xs">
          {([['grid', 'Grid'], ['rel', 'Relationships']] as const).map(([k, label]) => (
            <button key={k} onClick={() => setView(k)}
              className="rounded px-1.5 py-0.5"
              style={{ background: view === k ? '#27272a' : 'transparent',
                       color: view === k ? '#fafafa' : '#71717a' }}>
              {label}
            </button>
          ))}
        </span>
        <a href="/bids" className="ml-auto text-xs text-[#7d9096] hover:text-[#dbe4e6]">← bid screen</a>
      </div>
      {view === 'grid' && geo && tx ? <GridView geo={geo} tx={tx} /> : null}
      {view === 'grid' && (!geo || !tx) ? <div className="p-6 text-xs text-[#7d9096]">loading grid…</div> : null}
      <div style={{ display: view === 'rel' ? undefined : 'none' }}>
      <div className="mb-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[#93a6ab]">
        {Object.entries(KINDS).map(([k, v]) => (
          <button key={k} onClick={() => toggle(k)}
            className="flex items-center gap-1.5 rounded px-1 focus:outline-none focus:ring-1 focus:ring-neutral-500"
            style={{ opacity: off.has(k) ? 0.35 : 1 }}>
            <span className="inline-block h-0.5 w-4" style={{ background: v.color }} />
            {v.label}
          </button>
        ))}
        <span className="ml-auto flex items-center gap-2">
          <span>Size:</span>
          {([['mw', 'live MW'], ['dart', 'avg |basis|']] as const).map(([k, label]) => (
            <button key={k} onClick={() => setSizeBy(k)}
              className="rounded px-1.5 py-0.5 focus:outline-none focus:ring-1 focus:ring-neutral-500"
              style={{ background: sizeBy === k ? '#27272a' : 'transparent',
                       color: sizeBy === k ? '#fafafa' : '#71717a' }}>
              {label}
            </button>
          ))}
          <span className="text-[#61767e]">{graph.points} points · {graph.asOf}</span>
        </span>
      </div>

      <div ref={wrapRef} className="mx-auto w-full max-w-4xl">
        <svg viewBox={`0 0 ${size} ${size}`} width="100%" className="block select-none"
             onMouseLeave={() => setHover(null)}>
          {circles.filter(c => c.children).map((c, i) => (
            <circle key={`g${i}`} cx={c.x} cy={c.y} r={c.r} fill="none"
                    stroke="#3f3f46" strokeWidth={0.75} />
          ))}
          <g fill="none">
            {paths.filter(visible).map(p => (
              <path key={p.id} d={p.d} stroke={KINDS[p.kind].color}
                strokeWidth={lit(p) ? Math.max(1, p.value / 3) : 0.6}
                strokeOpacity={lit(p) ? (hover ? 0.95 : 0.45) : 0.06}
                strokeLinecap="round" />
            ))}
          </g>
          {leaves.map((n, i) => {
            const on = nodeLit(n.data.name)
            return (
              <g key={`n${i}`} onMouseEnter={() => setHover(n.data.name)}
                 onClick={() => setHover(n.data.name === hover ? null : n.data.name)}
                 style={{ cursor: 'pointer' }}>
                <circle cx={n.x} cy={n.y} r={n.r}
                  fill={n.data.name === hover ? '#e4e4e7' : '#18181b'}
                  stroke="#71717a" strokeWidth={0.75} opacity={on ? 1 : 0.25} />
                <text x={n.x} y={n.y + 3} textAnchor="middle"
                  fontSize={Math.min(11, Math.max(7, n.r / 2.6))}
                  fill={n.data.name === hover ? '#09090b' : '#a1a1aa'}
                  opacity={on ? 1 : 0.25} pointerEvents="none">
                  {n.r > 15 ? n.data.name : ''}
                </text>
              </g>
            )
          })}
        </svg>
      </div>

      <div className="mt-2 min-h-4 text-xs text-[#7d9096]">
        {hover && hoverNode ? (
          <>
            {hover} · {Math.round(hoverNode.value || 0).toLocaleString()}{sizeBy === 'mw' ? ' MW live' : ' $/MWh avg |basis|'} · {hoverLinks.length} linked
            {hoverLinks.filter(p => p.label).slice(0, 3).map(p => (
              <span key={p.id} className="ml-2 text-[#61767e]">[{p.label}]</span>
            ))}
          </>
        ) : 'Hover a node to isolate its relationships; click legend entries to toggle layers'}
      </div>
      </div>
    </div>
  )
}
